
# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

# Pipeline Automation Hub Funding Information
# 
# This project is currently maintained by volunteers and open-source contributors.
# If you find this project valuable and would like to support its development,
# consider the following options:
#
# 1. ⭐ Star the repository on GitHub
# 2. 🐛 Report bugs and suggest improvements
# 3. 🛠️ Contribute code, documentation, or tests  
# 4. 📢 Share the project with others who might benefit
# 5. 💼 Consider hiring contributors for commercial support
#
# For enterprise support or custom development:
# - Open an issue to discuss commercial support options
# - Contact maintainers through GitHub for consulting services
# - Consider sponsoring specific features or improvements
#
# All contributions, whether financial or through code, are greatly appreciated
# and help ensure the long-term sustainability of this project.
