jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Validate Requirements
      run: python scripts/automation/validate_requirements.py
    - name: Run Tests
      run: pytest tests/
name: QPLANT Requirements Validation
'on':
- push
- pull_request
